# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telabotaominhasreservas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class OP_MinhasReservas(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 621)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 841, 141))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(280, 0, 271, 71))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("fotos/carro.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(260, 70, 321, 61))
        self.widget_4.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setGeometry(QtCore.QRect(20, 10, 281, 41))
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight Condensed")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 150, 811, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(80, 170, 651, 261))
        self.widget_6.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.widget_6.setObjectName("widget_6")
        self.treeWidget = QtWidgets.QTreeWidget(self.widget_6)
        self.treeWidget.setGeometry(QtCore.QRect(10, 20, 631, 221))
        self.treeWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.treeWidget.headerItem().setFont(4, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 470, 301, 20))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 500, 101, 23))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(214, 214, 214);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(214, 214, 214);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 550, 75, 23))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(90, 500, 156, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Minhas Reservas"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "ID da Reserva"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Data e Hora "))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Tipo de Carro"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Local de Retirada"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Local de Devolução"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "Status da Reserva"))
        self.treeWidget.headerItem().setText(6, _translate("MainWindow", "Preço"))
        self.treeWidget.headerItem().setText(7, _translate("MainWindow", "Status da Reserva"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("MainWindow", "Deseja Cancelar Alguma Reserva? Se Sim, Informe o ID Dela:"))
        self.pushButton.setText(_translate("MainWindow", "Cancelar Reserva"))
        self.pushButton_2.setText(_translate("MainWindow", "Voltar"))
        self.label_6.setText(_translate("MainWindow", "ID:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = OP_MinhasReservas()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
