# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telasobrenos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Sobre_Nos(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 587)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 811, 531))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 350, 451, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("8a38caab-cc47-4ba8-9d59-7286c0446f79.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 101, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("fotos/images.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 490, 121, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(214, 214, 214);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(214, 214, 214);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:rgba(255,255,255,0.694118);\"><span style=\" font-family:\'-apple-system\',\'Roboto\',\'SegoeUI\',\'Segoe UI\',\'Helvetica Neue\',\'Helvetica\',\'Microsoft YaHei\',\'Meiryo UI\',\'Meiryo\',\'Arial Unicode MS\',\'sans-serif\'; font-size:16px; font-weight:600; font-style:italic; color:#111111;\">                          Sobre a LocaDrive</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'-apple-system\',\'Roboto\',\'SegoeUI\',\'Segoe UI\',\'Helvetica Neue\',\'Helvetica\',\'Microsoft YaHei\',\'Meiryo UI\',\'Meiryo\',\'Arial Unicode MS\',\'sans-serif\'; font-size:16px; font-weight:600; font-style:italic; color:#111111; background-color:rgba(255,255,255,0.694118);\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:rgba(255,255,255,0.694118);\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:rgba(255,255,255,0.694118);\"><span style=\" font-family:\'-apple-system\',\'Roboto\',\'SegoeUI\',\'Segoe UI\',\'Helvetica Neue\',\'Helvetica\',\'Microsoft YaHei\',\'Meiryo UI\',\'Meiryo\',\'Arial Unicode MS\',\'sans-serif\'; font-size:16px; font-style:italic; color:#111111; background-color:rgba(255,255,255,0.694118);\">A LocaDrive é uma empresa dedicada à locação de veículos, oferecendo uma ampla gama de opções para atender às diversas necessidades de nossos clientes. Nossa missão é fornecer um serviço de aluguel de carros de alta qualidade, garantindo a satisfação do cliente em cada interação.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'-apple-system\',\'Roboto\',\'SegoeUI\',\'Segoe UI\',\'Helvetica Neue\',\'Helvetica\',\'Microsoft YaHei\',\'Meiryo UI\',\'Meiryo\',\'Arial Unicode MS\',\'sans-serif\'; font-size:16px; font-style:italic; color:#111111; background-color:rgba(255,255,255,0.694118);\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:rgba(255,255,255,0.694118);\"><span style=\" font-family:\'-apple-system\',\'Roboto\',\'SegoeUI\',\'Segoe UI\',\'Helvetica Neue\',\'Helvetica\',\'Microsoft YaHei\',\'Meiryo UI\',\'Meiryo\',\'Arial Unicode MS\',\'sans-serif\'; font-size:16px; font-style:italic; color:#111111; background-color:rgba(255,255,255,0.694118);\">Nossa visão é ser reconhecida como a principal empresa de aluguel de carros no mercado, conhecida por sua confiabilidade, inovação e excelente atendimento ao cliente. Nossos valores centrais incluem integridade, compromisso com a qualidade e respeito pelos nossos clientes.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'-apple-system\',\'Roboto\',\'SegoeUI\',\'Segoe UI\',\'Helvetica Neue\',\'Helvetica\',\'Microsoft YaHei\',\'Meiryo UI\',\'Meiryo\',\'Arial Unicode MS\',\'sans-serif\'; font-size:16px; font-style:italic; color:#111111; background-color:rgba(255,255,255,0.694118);\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:rgba(255,255,255,0.694118);\"><span style=\" font-family:\'-apple-system\',\'Roboto\',\'SegoeUI\',\'Segoe UI\',\'Helvetica Neue\',\'Helvetica\',\'Microsoft YaHei\',\'Meiryo UI\',\'Meiryo\',\'Arial Unicode MS\',\'sans-serif\'; font-size:16px; font-style:italic; color:#111111; background-color:rgba(255,255,255,0.694118);\">O que nos diferencia é nosso compromisso com a qualidade. Cada carro em nossa frota é mantido em condições impecáveis e regularmente verificado para garantir a segurança e o conforto de nossos clientes. Além disso, nossa equipe dedicada está sempre pronta para ajudar os clientes a encontrar o veículo perfeito para suas necessidades.</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Sobre_Nos()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
